Sync with additional hardening

diff --git a/kickstart/provisioning_templates/snippet/Xsnippet_ISM.erb b/kickstart/provisioning_templates/snippet/Xsnippet_ISM.erb
--- a/kickstart/provisioning_templates/snippet/Xsnippet_ISM.erb
+++ b/kickstart/provisioning_templates/snippet/Xsnippet_ISM.erb
@@ -11,6 +11,7 @@ is_fedora = @host.operatingsystem.name == 'Fedora'
 os_major = @host.operatingsystem.major.to_i
 os_minor = @host.operatingsystem.minor.to_i
 use_ntp = host_param_true?('use-ntp') || (is_fedora && os_major < 16) || (rhel_compatible && os_major <= 7)
+use_systemd = (is_fedora && os_major < 16) || (rhel_compatible && os_major <= 7)
 %>
 
 echo "+++++++++++++++++++++++++ ISM Hardening Snippet +++++++++++++++++++++++++++++++"
@@ -24,9 +25,14 @@ systemctl disable postfix.service
 
 <%# ----------------------- KERNEL TUNING SECTION -----------------------------%>
 echo ">>> Kernel tuning parameters"
-cat << EOF > /etc/sysctl.conf
+<% if rhel_compatible && os_major == 6 %>
+cat << EOF > /etc/sysctl.d/05-hardening_el6.conf
 # Enable exec-sheield
 kernel.exec-shield = 1
+EOF
+<% end %>
+
+cat << EOF > /etc/sysctl.d/10-hardening.conf
 # Use process address space and heap randomisation
 kernel.randomize_va_space = 2
 # Prevent core dumps being created by suid binaries (EL6 only?)
@@ -51,16 +57,13 @@ net.ipv4.tcp_syncookies = 1
 net.ipv4.conf.all.rp_filter = 1
 net.ipv4.conf.default.rp_filter = 1
 
-# Network Tuning
-net.ipv4.tcp_max_syn_backlog = 4096
 EOF
 
-<%# Remove kernel exec-shield from sysctl.conf as it is no longer a tuning option
-for RHEL 7. ExecShield is enabled in the kernel by default now. %>
+<% if rhel_compatible && os_major >= 7 %>
 if (grep -q 'kernel\.exec-shield' /etc/sysctl.conf); then
   sed -Ei "/^(#kernel\.exec-shield|kernel\.exec-shield).*/d" /etc/sysctl.conf
 fi
-
+<% end %>
 
 <%# ----------------------- ULIMIT HARDENING SECTION --------------------------%>
 echo ">>> User limits configuration"
@@ -198,6 +201,7 @@ EOL
 
 
 <%# --------------------------- USBGUARD SECTION ------------------------------%>
+<% if (is_fedora && os_major >= 27) || (rhel_compatible && ((os_major == 7 && os_minor >= 4) || os_major >= 8)) -%>
 # RHEL 7.4 introduced usbguard for granular control of USB devices.
 if [ "$(virt-what)" == "" ]; then
   echo ">>> Installing usbguard"
@@ -207,17 +211,17 @@ if [ "$(virt-what)" == "" ]; then
   # Start the service
 #  systemctl enable usbguard && systemctl start usbguard
 fi
-
+<% end %>
 
 <%# ---------------------------- AUDIT SECTION --------------------------------%>
 echo ">>> Configure audit"
 # Configure system to use audispd plugin to pass audit events to syslog for streaming
-if [ $(grep -c '8.' /etc/redhat-release) -eq 1 ]; then
+<% if (is_fedora && os_major >= 28) || (rhel_compatible && os_major >= 8) -%>
   yum -q -y install audispd-plugins
   syslog_conf=/etc/audit/plugins.d/syslog.conf
-else
+<% else %>
   syslog_conf=/etc/audisp/plugins.d/syslog.conf
-fi
+<% end %>
 
 # Redirect audit to LOCAL0 facility so it can be suppressed from /var/log/messages
 sed -i 's/active = no/active = yes/g' ${syslog_conf}
@@ -239,15 +243,23 @@ EOF
 chmod 0600 /etc/audit/rules.d/90-ism_audit.rules
 
 # Enable the daemons
+<% if use_systemd -%>
 systemctl enable auditd
+<% else -%>
+chkconfig auditd on
+<% end -%>
 
 # Append audit=1 to default kernel options
+<% if (is_fedora && os_major >= 16) || (rhel_compatible && os_major >= 7) -%>
 sed -i '/GRUB_CMDLINE_LINUX.*$/{s/nofb/nofb audit=1/}' /etc/default/grub
+<% else -%>
+echo "** TODO: RHEL6 grub **************"
+<% end -%>
 
 
 <%# ---------------------------- SYSLOG SECTION -------------------------------%>
 echo ">>> Configure syslog"
-yum -q -y install rsyslog-gnutls rsyslog-relp
+<% if use_systemd -%>
 # Configure journalctl to save logs locally, and forward via rsyslog to remote host
 sed -i 's/#Storage=auto/Storage=persistent/g' /etc/systemd/journald.conf
 sed -i 's/#Compress=yes/Compress=yes/g' /etc/systemd/journald.conf
@@ -258,6 +270,7 @@ sed -i 's/#ForwardToSyslog=yes/ForwardToSyslog=yes/g' /etc/systemd/journald.conf
 # Logging journal and audit events to syslog overflows the rate limits - turn them off
 sed -i 's/#RateLimitInterval=.*/RateLimitInterval=0/' /etc/systemd/journald.conf
 sed -i 's/#RateLimitBurst=.*/RateLimitBurst=0/' /etc/systemd/journald.conf
+<% end -%>
 sed -i '/#### GLOBAL/a$imjournalRatelimitInterval 0' /etc/rsyslog.conf
 sed -i '/#### GLOBAL/a$imjournalRatelimitBurst 0' /etc/rsyslog.conf
 sed -i '/#### GLOBAL/a# Disable Rate Limiting' /etc/rsyslog.conf
@@ -271,7 +284,11 @@ sed -i 's/#$ModLoad immark/$ModLoad immark/g' /etc/rsyslog.conf
 <% if host_param('syslog_server') -%>
   echo "*.* @@<%= host_param('syslog_server') %>:514" >> /etc/rsyslog.conf
 <% end -%>
+<% if use_systemd -%>
 systemctl enable rsyslog
+<% else -%>
+chkconfig rsyslog on
+<% end -%>
 
 
 <%# --------------------------- SSH SECTION -----------------------------%>
@@ -304,31 +321,45 @@ for PAMFILE in /etc/pam.d/password-auth /etc/pam.d/system-auth; do
   # 2/3 Second last in the "auth" stack, just before pam_deny
   sed -i '/^auth\s*required\s*pam_deny.so$/iauth        [default=die] pam_faillock.so authfail deny=6 unlock_time=900 fail_interval=600' ${PAMFILE}
 
-  # 3/3 Top of the "account" stack, after pam_access (no options are required for pam_faillock here here)
+  # 3/3 Top of the "account" stack (no options are required for pam_faillock here)
   sed -i '/^account\s*required\s*pam_unix.so.*/iaccount     required      pam_faillock.so' ${PAMFILE}
 
   # Additional for RHEL 7 only due to differences in RHEL 7.1 and 7.2 default pam.d files. This removes additional lines which cause faillock not to work.
   # Remove Line "auth     [default=1 success=ok] pam_localuser.so
   # Replace Line "auth     [success=done ignore=ignore default=die] pam_unix.so try_first_pass with "auth  sufficient  pam_unix.so try_first_pass"
   # Replace Line "auth     sufficient   pam_sss.so forward_pass" with "auth   sufficient  pam_sss.so use_first_pass"
+  <% if rhel_compatible && os_major >= 7 -%>
   sed -i '/^auth\s*\[default.*pam_localuser.so/d' ${PAMFILE}
   sed -i 's/^auth\s*\[success.*pam_unix.so.*/auth        sufficient    pam_unix.so try_first_pass/' ${PAMFILE}
   sed -i 's/^auth.*sufficient.*pam_sss.so\s*forward_pass.*/auth         sufficient    pam_sss.so use_first_pass/' ${PAMFILE}
+  <% end -%>
 
   # RHEL 7.4 tweak to remove line that denies root login even from the console.
   # Remove line with "auth        [default=1 ignore=ignore success=ok] pam_succeed_if.so uid >= 1000 quiet"
+  <% if rhel_compatible && os_major >= 7 -%>
   sed -i '/^auth\s*\[default.*pam_succeed_if.so.*/d' ${PAMFILE}
+  <% end -%>
 
   ## Enforce password strength for local accounts with pam_cracklib ################################
   # Replace existing pam_pwquality which is first in the "password" stack.  This must be before pam_unix.
+  <% if rhel_compatible && os_major >= 7 -%>
   sed -i 's/^password\s*requisite\s*pam_pwquality.so.*$/password    requisite     pam_pwquality.so try_first_pass local_users_only retry=5 difok=4 minlen=11 minclass=3 maxrepeat=3/' ${PAMFILE}
+  <% else -%>
+  sed -i 's/^password\s*requisite\s*pam_cracklib.so.*$/password    requisite     pam_cracklib.so try_first_pass retry=5 difok=4 minlen=11 minclass=3 maxrepeat=3/' ${PAMFILE}'
+  <% end -%>
 
   ## Prevent password reuse ########################################################################
+  <% if rhel_compatible && os_major >= 7 -%>
   # On RHEL 7 use pam_pwhistory instead of the pam_unix "remember" option
   # 1/2 Remove the "remember" option from the pam_unix module if it exists
   sed -i '/^password\s*sufficient\s*pam_unix.so.*$/{s/ remember=[0-9]\{1,2\}//}' ${PAMFILE}
   # 2/2 Second entry in the "password" stack on RHEL 7 after pam_pwquality and before pam_unix
   sed -i '/^password\s*requisite\s*pam_pwquality.so.*$/apassword    requisite     pam_pwhistory.so use_authtok remember=8' ${PAMFILE}
+  <% else -%>
+  # For RHEL6 append remember=8 
+  sed -i '/^password\s*sufficient\s*pam_unix.so.*$/{s/$/ remember=8/}' ${PAMFILE}
+  <% end -%>
+
 
   ## Prevent blank passwords #######################################################################
   sed -i '/.*pam_unix.so.*$/{s/ nullok//}' ${PAMFILE}
@@ -336,10 +367,23 @@ for PAMFILE in /etc/pam.d/password-auth /etc/pam.d/system-auth; do
   ## Remove unused fingerprint scanner support #####################################################
   sed -i '/^auth\s*sufficient\s*pam_fprintd.so.*$/d' ${PAMFILE}
 
-  ## For systems that use local home directories e.g DMZ we use oddjobd to mount home directories
+  ## Display last failed login #####################################################################
+  <%# Not required on RHEL7+ %>
+  <% if rhel_compatible && os_major == 6 -%>
+  grep -q -E "^session\s*optional\s*pam_lastlog.so.*showfailed$" ${PAMFILE}
+  if [[ $? -ne 0 ]]; then
+    echo "session    optional    pam_lastlog.so nowtmp showfailed" >> ${PAMFILE}
+  fi
+  <% end -%>
+
+  ## For systems that use local home directories we use oddjobd to mount home directories
   # We will only add the pam_oddjob_mkhomedir.so if localhome parameter exists
   <% if host_param_true?('localhomedirs') %>
+  <% if rhel_compatible && os_major >= 7 -%>
     sed -i '/.*session\s*optional\s*pam_systemd.so.*$/asession     optional     pam_oddjob_mkhomedir.so umask=0077' ${PAMFILE}
+  <% else -%>
+    sed -i '/.*session\s*required\s*pam_limits.so.$/asession     optional     pam_oddjob_mkhomedir.so umask=0077' ${PAMFILE}
+  <% end -%>
   <% end %>
 
 done
@@ -367,10 +411,11 @@ done
 
 
 <%# ------------------------- DISABLE IPv6 SECTION ----------------------------%>
+<% unless host_param_false?('disable_ipv6') %>
 echo ">>> Disable IPv6"
 
 cat >> /etc/sysctl.d/20-ipv6.conf << EOL
-##
+#
 #  Ensure that the IPv6 kernel modules are included during OS instance build.
 #  Where possible, the use of IPv6 will be disabled in configuration of OS
 #  applications/utilities.
@@ -452,7 +497,7 @@ fi
 
 <%# Remove the DHCPv6 client listener firewall rule %>
 firewall-offline-cmd --remove-service dhcpv6-client
-
+<% end %>
 
 <%# ------------------------- ISSUE BANNER SECTION ----------------------------%>
 echo ">>> Set login banner"
@@ -469,7 +514,11 @@ EOF
 <%# ------------------------- SELINUX HARDENING SECTION ----------------------------%>
 echo ">>> Setup SELinux"
 # Add selinux=1 kernel option
+<% if (is_fedora && os_major >= 16) || (rhel_compatible && os_major >= 7) -%>
 sed -i '/GRUB_CMDLINE_LINUX.*$/{s/nofb/nofb selinux=1 enforcing=1/}' /etc/default/grub
+<% else -%>
+echo "** TODO: RHEL6 grub **************"
+<% end -%>
 
 <% unless host_param_true?('server_gui') -%>
   /usr/sbin/setsebool -P deny_ptrace 1
@@ -484,7 +533,11 @@ sed -i '/GRUB_CMDLINE_LINUX.*$/{s/nofb/nofb selinux=1 enforcing=1/}' /etc/defaul
 
 <%# Disable three-finger-salute reboot activation %>
 echo ">>> Disable Ctrl-Alt-Del"
+<% if use_systemd %>
 systemctl mask ctrl-alt-del.target && systemctl daemon-reload
+<% else %>
+echo "** TODO: RHEL6 ctrl-alt-del **************"
+<% end %>
 
 <%# Disable and/or remove not-required services %>
 <% if os_major == 6 -%>
